apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    name: backend-service
    app: to-do-app
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    name: backend-pod
    app: to-do-app