apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
spec:
  storageClassName: local-storage
  capacity: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/user/mongo/"