apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app-deployment
  labels:
    name: mongo-app-deployment
    app: to-do-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo-pod
      app: to-do-app
  template:
    metadata:
      name: mongo-pod
      labels:
        name: mongo-pod
        app: to-do-app
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017